source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.4'

# Rails本体
gem 'rails'

# データベースアダプタ
gem 'mysql2'

# Puma: RailsのデフォルトWebサーバー
gem 'puma'

# Action Cableで必要とされるRedis
gem 'redis'

# アセットパイプライン
gem 'sass-rails'
gem 'webpacker'

# ブラウザからの非同期更新
gem 'turbolinks'
gem 'jbuilder'

# 画像アップロードのためのライブラリ
gem 'image_processing'

# ユーザー認証
gem 'devise'

group :development, :test do
    # コード整形と静的解析
    gem 'rubocop-rails', require: false
    gem 'rubocop-performance', require: false
    gem 'pry-rails'
    # デバッグ用
    gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
    # ファイルの変更を検知してサーバーを再起動
    gem 'listen'
    # メールプレビュー
    gem 'letter_opener_web'
end

group :test do
    # テスト環境でのブラウザ操作の自動化
    gem 'capybara'
    gem 'selenium-webdriver'
    gem 'webdrivers'
end

group :production do
    # 本番環境でのエラーモニタリング
    gem 'sentry-raven'
end
