name: Revert PR #76

on:
  workflow_dispatch:

jobs:
  revert-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Revert PR
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git revert -m 1 $(git log --merges --oneline --reverse --ancestry-path HEAD...origin/main | grep 'Merge pull request #76' | tail -n 1 | awk '{print $1}')
          git push origin main